language: ruby
rvm:
- 2.2.5

install: gem install jekyll html-proofer
script: bundle install && bundle exec jekyll build && htmlproofer ./_site --allow-hash-href

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build