# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SyntaxRules
email: me@SyntaxRules.com
description: > # this means to ignore newlines until "baseurl:"
  HPC Articles. Projects. Software Consulting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://SyntaxRules.com" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  SyntaxRules
google_analytics: UA-89578181-1

sass:
  style: compressed

# Build settings
markdown: kramdown


# projects in header index
projects:
  - name: asciilang
    url: https://github.com/victorvoid/asciilang
  - name: vim-frontend
    url: https://github.com/victorvoid/vim-frontend
  - name: generator-capybara
    url: https://github.com/victorvoid/generator-capybara

media_link:
  - name: email
    url: mailto:me@SyntaxRules.com
#  - name: google-plus
#    url: google.com
  - name: github-alt
    url: https://github.com/SyntaxRules
#  - name: twitter
#    url: me@SyntaxRules.com
  - name: rss
    url: /feed.xml

nav_pages:
  - name: Atricles
    permalink: /articles.html
  - name: Projects
    permalink: /projects.html
  - name: Consulting
    permalink: /consulting.html

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
